### ISSUE TITLE
[Init] 프로젝트 초기 셋팅

### ISSUE THREAD

**Issue by JeYeongR** [Stamfood/Stamfood-BE#1]
## 📑 Description

프로젝트 초기 셋팅했습니다.

## ✅ Tasks

- [x] 기술 스택 정하기
- [x] 이슈 템플릿 생성
- [x] PR 템플릿 생성

## 👨‍💻️️ References

구글링
