### ISSUE TITLE
[Feat] 회원 Entity / Repository 생성 및 DB 연결 확인

### ISSUE THREAD

**Issue by hoonii2** [Stamfood/Stamfood-BE#4]
## 📑 Description

회원 Entity / Repository 생성 및 DB 연결 확인

## ✅ Tasks

- [ ] 회원 Entity 생성
- [ ] 회원 Repository Interface 및 Repository Impl 구현
- [ ] Repository DB 연결 테스트
