### ISSUE TITLE
[Feat] Auditing 관련 설정 및 Base Entity 작성

### ISSUE THREAD

**Issue by hoonii2** [Stamfood/Stamfood-BE#5]
## 📑 Description

Auditing 관련 설정 및 Base Entity 작성

## ✅ Tasks

- [ ] Spring Boot JPA Auditing 설정
- [ ] Base Entity 작성
- [ ] Auditing 동작 확인
