### ISSUE TITLE
[Feat] 식당 도장 Entity / 패키지 구조 정리

### ISSUE THREAD

**Issue by lala9663** [Stamfood/Stamfood-BE#7]
## 📑 Description

패키지 기본틀 나누기, 
식당, 도장 엔티티 만들어두기

## ✅ Tasks

- [x] 식당 Entity 생성
- [x] 도장 Entity 생성
- [x] 패키지 구조 나누기
