### ISSUE TITLE
[Feat] 코스 생성 API 구현

### ISSUE THREAD

**Issue by JeYeongR** [Stamfood/Stamfood-BE#9]
## 📑 Description
코스 생성 API 구현

아직 구현이 안 된 엔티티는 간단하게 만들어서 사용함

## ✅ Tasks

- [ ] API 관련 엔티티 생성
- [ ] 서비스 로직 구현
- [ ] 테스트 코드 구현
